/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import MetodosBaDa.ConexionBaDa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zanahoria Pc
 */
public class ActiviadesDeDesarrollador extends javax.swing.JFrame {
    String user, nombredeusuario;
    int numTareas;
    public static int sesiondeusuario;
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form ActiviadesDeDesarrollador
     */
    public ActiviadesDeDesarrollador() {
        initComponents();
        user = Cliente.user;
        sesiondeusuario=1;
       
       
        setSize(650, 440);
        setResizable(false);
        setTitle("Administrador -Sesión de " + user);
        setLocationRelativeTo(null);
       
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        try{
            Connection cn = ConexionBaDa.conectar();
            PreparedStatement pst = cn.prepareStatement( "select nombre_usuario,tareas from desarrolladores where usuario = '" + user + "'");
           
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombredeusuario = rs.getString("nombre_usuario");
                numTareas = rs.getInt("tareas");
                NombreUsuario.setText(nombredeusuario);
            }
           
            cn.close();
           
            Connection con = ConexionBaDa.conectar();
            PreparedStatement pst2 = con.prepareStatement("select numtarea,usuario,pendiente,progreso,terminada,entregada from tareas where usuario = '" + user + "'");
           
            ResultSet rs2 = pst2.executeQuery();
            TablaDeUsuario = new JTable(model);
            jScrollPane1.setViewportView(TablaDeUsuario);

            model.addColumn("numtarea");
            model.addColumn("Usuario");
            model.addColumn("Pendiente");
            model.addColumn("En progreso");
            model.addColumn("Terminada");
            model.addColumn("Entregada");
         
       
            while(rs2.next()){
                Object[] fila = new Object[6];
               
                for(int i=0;i<6;i++){
                    fila[i] = rs2.getObject(i+1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch(Exception e){
            System.err.println("Error en conexion desde Administrador");
            JOptionPane.showMessageDialog(null, "Contactar ayuda");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDeUsuario = new javax.swing.JTable();
        txtActividad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EstadoActividad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaDeUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Primera", "segunda", "Tercera", "cuarta"
            }
        ));
        jScrollPane1.setViewportView(TablaDeUsuario);

        jLabel2.setText("Interfaz de: ");

        jLabel3.setText("Nombre de la actividad:");

        jLabel4.setText("Estados de la actividad");

        EstadoActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"En Progreso","terminada","entregada"}));
        EstadoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 String itemSeleccionado = EstadoActividad.getSelectedItem().toString();
        if(itemSeleccionado.equals("Realizar tarea"))
                EstadoActividadActionPerformed(evt, "progreso");
        if(itemSeleccionado.equals("Terminar tarea"))
                EstadoActividadActionPerformed(evt, "terminada");
        if(itemSeleccionado.equals("Entregar tarea"))
                EstadoActividadActionPerformed(evt, "entregada");
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EstadoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)
                            .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(NombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstadoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadoActividadActionPerformed(java.awt.event.ActionEvent evt,String var ) {//GEN-FIRST:event_EstadoActividadActionPerformed
        int tarea = 0;
        String actividades;
       
        actividades = txtActividad.getText().trim();
        try {
        tarea = Integer.parseInt(txtActividad.getText().trim());            
            try{
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Realmente desea hacer esta accion?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmar == JOptionPane.YES_OPTION){
           Connection cn = ConexionBaDa.conectar();
                     PreparedStatement pst = cn.prepareStatement("select numtarea," + var + " from tareas where usuario = '" + user + "' and numtarea = '"+ tarea +"'");
                     ResultSet rs = pst.executeQuery();
                     
                     if(rs.next() && rs.getInt(var) == 0){
                         try{
                             //METODO PARA ACTUALIZAR BASE DE DATOS
                             Connection con = ConexionBaDa.conectar();
                             PreparedStatement pst2 = con.prepareStatement("update tareas set " + var + " = ? where usuario = '" + user + "' and numtarea = '"+ tarea +"'");
                             pst2.setInt(1, 1);
                             
                             pst2.executeUpdate();
                             con.close();
                             JOptionPane.showMessageDialog(null, "Tarea en " + var);
                             this.dispose();
                         } catch(SQLException e){
                             System.err.println("Error" + e);
                         }
                         java.awt.EventQueue.invokeLater(new Runnable() {
                             public void run() {
                                 new ActiviadesDeDesarrollador().setVisible(true);
                             }
                         });
                         
                         cn.close();
                     } else{
                         JOptionPane.showMessageDialog(null, "La tarea ya se encuentra en el estado seleccionado");
                         cn.close();                    
                     }
            }
               
            } catch(SQLException e){
                System.err.println("Error en validar numero de tarea" + e);
                JOptionPane.showMessageDialog(null, "Error al comparar la tarea. Contactar ayuda");
            }
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero entero");        
        }
    }//GEN-LAST:event_EstadoActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActiviadesDeDesarrollador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActiviadesDeDesarrollador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActiviadesDeDesarrollador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActiviadesDeDesarrollador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActiviadesDeDesarrollador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EstadoActividad;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JTable TablaDeUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtActividad;
    // End of variables declaration//GEN-END:variables
}
