/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import MetodosBaDa.ConexionBaDa;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zanahoria Pc
 */
public class RegistroDeActividades extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDeActividades
     */
    public RegistroDeActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumeroDeActividad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        RevisarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel1.setText("Registro De Actividad");

        jLabel2.setText("Numero de Actividad");

        jLabel3.setText("Usuario");

        RevisarActividad.setText("RegistarActividad");
        RevisarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevisarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RevisarActividad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumeroDeActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumeroDeActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(RevisarActividad)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RevisarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevisarActividadActionPerformed
        int tarea,validacion=0,numTareas=0;
        String username,tareas;
        
        tareas = NumeroDeActividad.getText().trim();
        tarea = Integer.parseInt(NumeroDeActividad.getText().trim());
        username = Usuario.getText().trim();
        if(tareas.equals("")){
           NumeroDeActividad.setBackground(Color.red);
           validacion++;
       }
       
       if(username.equals("")){
           Usuario.setBackground(Color.red);
           validacion++;
       }
       
       
       
       try{
           Connection cn = ConexionBaDa.conectar();
           PreparedStatement pst1 = cn.prepareStatement("select usuario from desarrolladores where usuario = '" + username + "'");
           ResultSet rs1 = pst1.executeQuery();
           if(rs1.next()){
           
           Connection con = ConexionBaDa.conectar();
           PreparedStatement pst = con.prepareStatement("select numtarea from tareas where usuario = '" + username + "' and numtarea = '"+ tarea +"'");
           ResultSet rs = pst.executeQuery();
           
           if(rs.next()){
               NumeroDeActividad.setBackground(Color.red);
               JOptionPane.showMessageDialog(null, "Tarea repetida");
               con.close();
           } else{
               
               con.close();
               if(validacion == 0){
                   try{
                       //METODO PARA ACTUALIZAR BASE DE DATOS
                      Connection con1 = ConexionBaDa.conectar();
                       PreparedStatement pst2 = con1.prepareStatement("insert into tareas values (?,?,?,?,?,?,?)");
                       pst2.setInt(1, 0);
                       pst2.setString(2, username);
                       pst2.setInt(3, 1);
                       pst2.setInt(4, 0);
                       pst2.setInt(5, 0);
                       pst2.setInt(6, 0);
                       pst2.setInt(7, tarea);
                       //pst2.setString(8, );
                       //pst2.setString(7, user);
                       
                       pst2.executeUpdate();
                       
                       
                       Connection con2 = ConexionBaDa.conectar();
            PreparedStatement pst3 = con2.prepareStatement( "select tareas from desarrolladores where usuario = '" + username + "'");
           
            ResultSet rs3 = pst3.executeQuery();
            if(rs3.next()){
                numTareas = rs3.getInt("tareas");
                
                Connection con3 = ConexionBaDa.conectar();
                             PreparedStatement pst4 = con3.prepareStatement("update desarrolladores set tareas = ? where usuario = '" + username + "'");
                             pst4.setInt(1, numTareas+1);
                             
                             pst4.executeUpdate();
                             con3.close();
            }
                       
                       
                       
                       con1.close();
                       con2.close();
                       
                       Limpiar();
                       NumeroDeActividad.setBackground(Color.green);
                       Usuario.setBackground(Color.green);
                       //txt_password.setBackground(Color.green);
                       //txt_nombre.setBackground(Color.green);
                       JOptionPane.showMessageDialog(null, "Guardado correctamente");
                       this.dispose();
                   } catch(SQLException e){
                       System.err.println("No se puede guardar la Actividad" + e);
                   }
               }
           }
           } else{
               JOptionPane.showMessageDialog(null, "Tus credenciales de inicio de sesion no coinciden con una cuenta en nuestros sistemas");
           }
       } catch(SQLException e){
           System.err.println("Tus credenciales de inicio de sesion no coinciden con una cuenta en nuestros sistemas" + e);
           JOptionPane.showMessageDialog(null, "Tus credenciales de inicio de sesion no coinciden con una cuenta en nuestros sistemas");
       }

        // TODO add your handling code here:
    }//GEN-LAST:event_RevisarActividadActionPerformed
    public void Limpiar(){
            NumeroDeActividad.setText("");
         Usuario.setText("");
        } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeActividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumeroDeActividad;
    private javax.swing.JButton RevisarActividad;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
       
}


