
package Proyecto;

import MetodosBaDa.ConexionBaDa;
import MetodosBaDa.MetodosBaDa;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zanahoria Pc
 */
public class RegistroUsuario extends javax.swing.JFrame {
    
    
    public RegistroUsuario() {
        initComponents();
    }
    MetodosBaDa metodos = new MetodosBaDa();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreusuario = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        NombrePerfil = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        BotonGuardar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        RangoDeAcceso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO USUARIO");

        jLabel2.setText("Nombre Usuario:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("edad");

        jLabel5.setText("contraseña");

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        RangoDeAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lider","desarrollador" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(NombrePerfil)
                                .addComponent(nombreusuario))
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RangoDeAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BotonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RangoDeAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonGuardar)
                .addGap(18, 18, 18)
                .addComponent(BotonRegresar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        Cliente ventana = new Cliente();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        
       int rango, validacion=0;
       String  NombreUsuario, contrasena, nombredeperfil, edades, nivel="";
       
       
       NombreUsuario = nombreusuario.getText().trim();
       contrasena = password.getText().trim();
       nombredeperfil = NombrePerfil.getText().trim();
       edades = edad.getText().trim();
       rango = RangoDeAcceso.getSelectedIndex() + 1;
       
       if(NombreUsuario.equals("")){
           nombreusuario.setBackground(Color.red);
           validacion++;
       }
       
       if(contrasena.equals("")){
           password.setBackground(Color.red);
           validacion++;
       }
       
       if(nombredeperfil.equals("")){
           NombrePerfil.setBackground(Color.red);
           validacion++;
       }
       
       if(edades.equals("")){
           edad.setBackground(Color.red);
           validacion++;
       }
       
       if(rango == 1){
           nivel = "Lider";
       }else if(rango == 2){
           nivel = "Desarrollador";
       }
       
       try{
           Connection cn = ConexionBaDa.conectar();
           PreparedStatement pst = cn.prepareStatement("select usuario from desarrolladores where usuario = '" + contrasena + "'");
           ResultSet rs = pst.executeQuery();
           
           if(rs.next()){
               nombreusuario.setBackground(Color.red);
               JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible");
               cn.close();
           } else{
               
               cn.close();
               if(validacion == 0){
                   try{
                       Connection con = ConexionBaDa.conectar();
                       PreparedStatement pst2 = con.prepareStatement("insert into desarrolladores values (?,?,?,?,?,?,?)");
                       pst2.setInt(1, 0);
                       pst2.setString(2, NombreUsuario);
                       pst2.setString(3, contrasena);
                       pst2.setString(4, nombredeperfil);
                       pst2.setString(5, edades);
                       pst2.setString(6, nivel);
                       pst2.setInt(7, 0);
                       pst2.executeUpdate();
                       con.close();
                       
                       Limpiar();
                       JOptionPane.showMessageDialog(null, "Registro exitoso");
                       this.dispose();
                   } catch(SQLException e){
                       System.err.println("surgio un inconveniente" + e);
                   }
               }else{
                   JOptionPane.showMessageDialog(null, "revisa tus Datos");
               }
               
           }
       } catch(SQLException e){
           System.err.println("no se pudo confirmar tu usuario" + e);
           JOptionPane.showMessageDialog(null, "Error al comparar usuario");
       }
    }//GEN-LAST:event_BotonGuardarActionPerformed
    
    public void Limpiar(){
        nombreusuario.setText("");
        password.setText("");
        NombrePerfil.setText("");
        edad.setText("");
        RangoDeAcceso.setSelectedIndex(0);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTextField NombrePerfil;
    private javax.swing.JComboBox<String> RangoDeAcceso;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreusuario;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
